# Generated by Django 5.2.1 on 2025-06-02 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DominoPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.CharField(choices=[('mae', 'Mãe'), ('pai', 'Pai'), ('irmao', 'Irmão'), ('avo_fem', 'Avó'), ('avo_masc', 'Avô'), ('tia', 'Tia'), ('tio', 'Tio')], max_length=10)),
                ('right', models.CharField(choices=[('mae', 'Mãe'), ('pai', 'Pai'), ('irmao', 'Irmão'), ('avo_fem', 'Avó'), ('avo_masc', 'Avô'), ('tia', 'Tia'), ('tio', 'Tio')], max_length=10)),
            ],
            options={
                'unique_together': {('left', 'right')},
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GamePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('in_deck', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='domino_online.game')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domino_online.dominopiece')),
            ],
            options={
                'unique_together': {('game', 'piece')},
            },
        ),
    ]
