# Generated by Django 5.2.1 on 2025-06-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domino_online', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamepiece',
            name='in_deck',
        ),
        migrations.AlterField(
            model_name='gamepiece',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
