# Generated by Django 5.2.1 on 2025-06-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domino_online', '0002_remove_gamepiece_in_deck_alter_gamepiece_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepiece',
            name='orientation',
            field=models.CharField(choices=[('H', 'Horizontal'), ('V', 'Vertical')], default='H', max_length=1),
        ),
    ]
